/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_download_gray                                    *
* Dimensions:  12 * 12                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_download_gray;

static GUI_CONST_STORAGE unsigned char _acicon_download_gray[] = {
  /* RLE: 004 Pixels @ 000,000 */ 4, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,000 */ 0, 4, 0x86, 0x31, 0x8A, 0x52, 0x8A, 0x52, 0x86, 0x31, 
  /* RLE: 008 Pixels @ 008,000 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,001 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 008 Pixels @ 008,001 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,002 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 008 Pixels @ 008,002 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,003 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 008 Pixels @ 008,003 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,004 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 004 Pixels @ 008,004 */ 4, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 000,005 */ 4, 0x08, 0x42, 
  /* RLE: 004 Pixels @ 004,005 */ 4, 0x8A, 0x52, 
  /* RLE: 004 Pixels @ 008,005 */ 4, 0x08, 0x42, 
  /* RLE: 001 Pixels @ 000,006 */ 1, 0x86, 0x31, 
  /* RLE: 010 Pixels @ 001,006 */ 10, 0x8A, 0x52, 
  /* ABS: 003 Pixels @ 011,006 */ 0, 3, 0x86, 0x31, 0x00, 0x00, 0x86, 0x31, 
  /* RLE: 008 Pixels @ 002,007 */ 8, 0x8A, 0x52, 
  /* ABS: 005 Pixels @ 010,007 */ 0, 5, 0x86, 0x31, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x86, 0x31, 
  /* RLE: 006 Pixels @ 003,008 */ 6, 0x8A, 0x52, 
  /* RLE: 001 Pixels @ 009,008 */ 1, 0x08, 0x42, 
  /* RLE: 005 Pixels @ 010,008 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,009 */ 1, 0x08, 0x42, 
  /* RLE: 004 Pixels @ 004,009 */ 4, 0x8A, 0x52, 
  /* RLE: 001 Pixels @ 008,009 */ 1, 0x08, 0x42, 
  /* RLE: 007 Pixels @ 009,009 */ 7, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,010 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 009 Pixels @ 008,010 */ 9, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 005,011 */ 0, 2, 0x08, 0x42, 0x08, 0x42, 
  /* RLE: 005 Pixels @ 007,011 */ 5, 0x00, 0x00, 
  0
};  // 128 for 144 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_download_gray = {
  12, // xSize
  12, // ySize
  24, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_download_gray,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
