/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_upload_gray                                      *
* Dimensions:  12 * 12                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_upload_gray;

static GUI_CONST_STORAGE unsigned char _acicon_upload_gray[] = {
  /* RLE: 005 Pixels @ 000,000 */ 5, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 005,000 */ 0, 2, 0x08, 0x42, 0x08, 0x42, 
  /* RLE: 009 Pixels @ 007,000 */ 9, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,001 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 007 Pixels @ 008,001 */ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,002 */ 1, 0x08, 0x42, 
  /* RLE: 004 Pixels @ 004,002 */ 4, 0x8A, 0x52, 
  /* RLE: 001 Pixels @ 008,002 */ 1, 0x08, 0x42, 
  /* RLE: 005 Pixels @ 009,002 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 002,003 */ 1, 0x08, 0x42, 
  /* RLE: 006 Pixels @ 003,003 */ 6, 0x8A, 0x52, 
  /* ABS: 005 Pixels @ 009,003 */ 0, 5, 0x86, 0x31, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x86, 0x31, 
  /* RLE: 008 Pixels @ 002,004 */ 8, 0x8A, 0x52, 
  /* ABS: 003 Pixels @ 010,004 */ 0, 3, 0x86, 0x31, 0x00, 0x00, 0x86, 0x31, 
  /* RLE: 010 Pixels @ 001,005 */ 10, 0x8A, 0x52, 
  /* RLE: 001 Pixels @ 011,005 */ 1, 0x86, 0x31, 
  /* RLE: 004 Pixels @ 000,006 */ 4, 0x08, 0x42, 
  /* RLE: 004 Pixels @ 004,006 */ 4, 0x8A, 0x52, 
  /* RLE: 004 Pixels @ 008,006 */ 4, 0x08, 0x42, 
  /* RLE: 004 Pixels @ 000,007 */ 4, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,007 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 008 Pixels @ 008,007 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,008 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 008 Pixels @ 008,008 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,009 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 008 Pixels @ 008,009 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,010 */ 0, 4, 0x08, 0x42, 0x8A, 0x52, 0x8A, 0x52, 0x08, 0x42, 
  /* RLE: 008 Pixels @ 008,010 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,011 */ 0, 4, 0x86, 0x31, 0x8A, 0x52, 0x8A, 0x52, 0x86, 0x31, 
  /* RLE: 004 Pixels @ 008,011 */ 4, 0x00, 0x00, 
  0
};  // 128 for 144 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_upload_gray = {
  12, // xSize
  12, // ySize
  24, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_upload_gray,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
