/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_information_background_double                    *
* Dimensions:  30 * 20                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_information_background_double;

static GUI_CONST_STORAGE unsigned char _acicon_information_background_double[] = {
  /* RLE: 006 Pixels @ 000,000 */ 6, 0x00, 0x00, 
  /* ABS: 003 Pixels @ 006,000 */ 0, 3, 0x8A, 0x52, 0x14, 0xA5, 0x9A, 0xD6, 
  /* RLE: 012 Pixels @ 009,000 */ 12, 0x9E, 0xF7, 
  /* ABS: 003 Pixels @ 021,000 */ 0, 3, 0x9A, 0xD6, 0x14, 0xA5, 0x8A, 0x52, 
  /* RLE: 010 Pixels @ 024,000 */ 10, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 004,001 */ 0, 2, 0x8A, 0x52, 0x9A, 0xD6, 
  /* RLE: 018 Pixels @ 006,001 */ 18, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 024,001 */ 0, 2, 0x9A, 0xD6, 0x8A, 0x52, 
  /* RLE: 007 Pixels @ 026,001 */ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,002 */ 1, 0x10, 0x84, 
  /* RLE: 022 Pixels @ 004,002 */ 22, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 026,002 */ 1, 0x10, 0x84, 
  /* RLE: 005 Pixels @ 027,002 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 002,003 */ 1, 0x10, 0x84, 
  /* RLE: 024 Pixels @ 003,003 */ 24, 0x9E, 0xF7, 
  /* ABS: 005 Pixels @ 027,003 */ 0, 5, 0x10, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8A, 0x52, 
  /* RLE: 026 Pixels @ 002,004 */ 26, 0x9E, 0xF7, 
  /* ABS: 004 Pixels @ 028,004 */ 0, 4, 0x8A, 0x52, 0x00, 0x00, 0x00, 0x00, 0x1C, 0xE7, 
  /* RLE: 026 Pixels @ 002,005 */ 26, 0x9E, 0xF7, 
  /* ABS: 003 Pixels @ 028,005 */ 0, 3, 0x1C, 0xE7, 0x00, 0x00, 0x8A, 0x52, 
  /* RLE: 028 Pixels @ 001,006 */ 28, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 029,006 */ 0, 2, 0x8A, 0x52, 0x14, 0xA5, 
  /* RLE: 028 Pixels @ 001,007 */ 28, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 029,007 */ 0, 2, 0x14, 0xA5, 0x9A, 0xD6, 
  /* RLE: 028 Pixels @ 001,008 */ 28, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 029,008 */ 1, 0x9A, 0xD6, 
  /* RLE: 030 Pixels @ 000,009 */ 30, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 000,010 */ 1, 0x1C, 0xE7, 
  /* RLE: 029 Pixels @ 001,010 */ 29, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 000,011 */ 1, 0x9A, 0xD6, 
  /* RLE: 028 Pixels @ 001,011 */ 28, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 029,011 */ 0, 2, 0x9A, 0xD6, 0x14, 0xA5, 
  /* RLE: 028 Pixels @ 001,012 */ 28, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 029,012 */ 0, 2, 0x14, 0xA5, 0x8A, 0x52, 
  /* RLE: 028 Pixels @ 001,013 */ 28, 0x9E, 0xF7, 
  /* ABS: 003 Pixels @ 029,013 */ 0, 3, 0x8A, 0x52, 0x00, 0x00, 0x1C, 0xE7, 
  /* RLE: 026 Pixels @ 002,014 */ 26, 0x9E, 0xF7, 
  /* ABS: 004 Pixels @ 028,014 */ 0, 4, 0x1C, 0xE7, 0x00, 0x00, 0x00, 0x00, 0x8A, 0x52, 
  /* RLE: 026 Pixels @ 002,015 */ 26, 0x9E, 0xF7, 
  /* ABS: 005 Pixels @ 028,015 */ 0, 5, 0x8A, 0x52, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x84, 
  /* RLE: 024 Pixels @ 003,016 */ 24, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 027,016 */ 1, 0x10, 0x84, 
  /* RLE: 005 Pixels @ 028,016 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,017 */ 1, 0x92, 0x94, 
  /* RLE: 022 Pixels @ 004,017 */ 22, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 026,017 */ 1, 0x92, 0x94, 
  /* RLE: 007 Pixels @ 027,017 */ 7, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 004,018 */ 0, 2, 0x8A, 0x52, 0x9A, 0xD6, 
  /* RLE: 018 Pixels @ 006,018 */ 18, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 024,018 */ 0, 2, 0x9A, 0xD6, 0x8A, 0x52, 
  /* RLE: 010 Pixels @ 026,018 */ 10, 0x00, 0x00, 
  /* ABS: 003 Pixels @ 006,019 */ 0, 3, 0x8A, 0x52, 0x14, 0xA5, 0x9A, 0xD6, 
  /* RLE: 012 Pixels @ 009,019 */ 12, 0x9E, 0xF7, 
  /* ABS: 003 Pixels @ 021,019 */ 0, 3, 0x9A, 0xD6, 0x14, 0xA5, 0x8A, 0x52, 
  /* RLE: 006 Pixels @ 024,019 */ 6, 0x00, 0x00, 
  0
};  // 214 for 600 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_information_background_double = {
  30, // xSize
  20, // ySize
  60, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_information_background_double,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
