/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_download_white                                   *
* Dimensions:  12 * 12                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_download_white;

static GUI_CONST_STORAGE unsigned char _acicon_download_white[] = {
  /* RLE: 004 Pixels @ 000,000 */ 4, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,000 */ 0, 4, 0x92, 0x94, 0x9A, 0xD6, 0x9A, 0xD6, 0x92, 0x94, 
  /* RLE: 008 Pixels @ 008,000 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,001 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 008 Pixels @ 008,001 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,002 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 008 Pixels @ 008,002 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,003 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 008 Pixels @ 008,003 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,004 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 004 Pixels @ 008,004 */ 4, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 000,005 */ 0, 4, 0x14, 0xA5, 0x96, 0xB5, 0x18, 0xC6, 0x96, 0xB5, 
  /* RLE: 004 Pixels @ 004,005 */ 4, 0x9A, 0xD6, 
  /* RLE: 003 Pixels @ 008,005 */ 3, 0x96, 0xB5, 
  /* ABS: 002 Pixels @ 011,005 */ 0, 2, 0x14, 0xA5, 0x10, 0x84, 
  /* RLE: 010 Pixels @ 001,006 */ 10, 0x9A, 0xD6, 
  /* ABS: 003 Pixels @ 011,006 */ 0, 3, 0x10, 0x84, 0x00, 0x00, 0x92, 0x94, 
  /* RLE: 008 Pixels @ 002,007 */ 8, 0x9A, 0xD6, 
  /* ABS: 005 Pixels @ 010,007 */ 0, 5, 0x92, 0x94, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x92, 0x94, 
  /* RLE: 006 Pixels @ 003,008 */ 6, 0x9A, 0xD6, 
  /* RLE: 001 Pixels @ 009,008 */ 1, 0x92, 0x94, 
  /* RLE: 005 Pixels @ 010,008 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,009 */ 1, 0x14, 0xA5, 
  /* RLE: 004 Pixels @ 004,009 */ 4, 0x9A, 0xD6, 
  /* RLE: 001 Pixels @ 008,009 */ 1, 0x14, 0xA5, 
  /* RLE: 006 Pixels @ 009,009 */ 6, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 003,010 */ 0, 6, 0x82, 0x10, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 0x82, 0x10, 
  /* RLE: 007 Pixels @ 009,010 */ 7, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,011 */ 0, 4, 0x82, 0x10, 0x96, 0xB5, 0x96, 0xB5, 0x82, 0x10, 
  /* RLE: 004 Pixels @ 008,011 */ 4, 0x00, 0x00, 
  0
};  // 148 for 144 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_download_white = {
  12, // xSize
  12, // ySize
  24, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_download_white,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
