/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_information_background_single                    *
* Dimensions:  21 * 20                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_information_background_single;

static GUI_CONST_STORAGE unsigned char _acicon_information_background_single[] = {
  /* RLE: 006 Pixels @ 000,000 */ 6, 0x00, 0x00, 
  /* ABS: 009 Pixels @ 006,000 */ 0, 9, 0x8A, 0x52, 0x14, 0xA5, 0x9A, 0xD6, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 0x9A, 0xD6, 0x14, 0xA5, 0x8A, 0x52, 
  /* RLE: 010 Pixels @ 015,000 */ 10, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 004,001 */ 0, 2, 0x8A, 0x52, 0x9A, 0xD6, 
  /* RLE: 009 Pixels @ 006,001 */ 9, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 015,001 */ 0, 2, 0x9A, 0xD6, 0x8A, 0x52, 
  /* RLE: 007 Pixels @ 017,001 */ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,002 */ 1, 0x10, 0x84, 
  /* RLE: 013 Pixels @ 004,002 */ 13, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 017,002 */ 1, 0x10, 0x84, 
  /* RLE: 005 Pixels @ 018,002 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 002,003 */ 1, 0x10, 0x84, 
  /* RLE: 015 Pixels @ 003,003 */ 15, 0x9E, 0xF7, 
  /* ABS: 005 Pixels @ 018,003 */ 0, 5, 0x10, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8A, 0x52, 
  /* RLE: 017 Pixels @ 002,004 */ 17, 0x9E, 0xF7, 
  /* ABS: 004 Pixels @ 019,004 */ 0, 4, 0x8A, 0x52, 0x00, 0x00, 0x00, 0x00, 0x1C, 0xE7, 
  /* RLE: 017 Pixels @ 002,005 */ 17, 0x9E, 0xF7, 
  /* ABS: 003 Pixels @ 019,005 */ 0, 3, 0x1C, 0xE7, 0x00, 0x00, 0x8A, 0x52, 
  /* RLE: 019 Pixels @ 001,006 */ 19, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 020,006 */ 0, 2, 0x8A, 0x52, 0x14, 0xA5, 
  /* RLE: 019 Pixels @ 001,007 */ 19, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 020,007 */ 0, 2, 0x14, 0xA5, 0x9A, 0xD6, 
  /* RLE: 019 Pixels @ 001,008 */ 19, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 020,008 */ 1, 0x9A, 0xD6, 
  /* RLE: 021 Pixels @ 000,009 */ 21, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 000,010 */ 1, 0x1C, 0xE7, 
  /* RLE: 020 Pixels @ 001,010 */ 20, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 000,011 */ 1, 0x9A, 0xD6, 
  /* RLE: 019 Pixels @ 001,011 */ 19, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 020,011 */ 0, 2, 0x9A, 0xD6, 0x14, 0xA5, 
  /* RLE: 019 Pixels @ 001,012 */ 19, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 020,012 */ 0, 2, 0x14, 0xA5, 0x8A, 0x52, 
  /* RLE: 019 Pixels @ 001,013 */ 19, 0x9E, 0xF7, 
  /* ABS: 003 Pixels @ 020,013 */ 0, 3, 0x8A, 0x52, 0x00, 0x00, 0x1C, 0xE7, 
  /* RLE: 017 Pixels @ 002,014 */ 17, 0x9E, 0xF7, 
  /* ABS: 004 Pixels @ 019,014 */ 0, 4, 0x1C, 0xE7, 0x00, 0x00, 0x00, 0x00, 0x8A, 0x52, 
  /* RLE: 017 Pixels @ 002,015 */ 17, 0x9E, 0xF7, 
  /* ABS: 005 Pixels @ 019,015 */ 0, 5, 0x8A, 0x52, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x84, 
  /* RLE: 015 Pixels @ 003,016 */ 15, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 018,016 */ 1, 0x10, 0x84, 
  /* RLE: 005 Pixels @ 019,016 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,017 */ 1, 0x92, 0x94, 
  /* RLE: 013 Pixels @ 004,017 */ 13, 0x9E, 0xF7, 
  /* RLE: 001 Pixels @ 017,017 */ 1, 0x92, 0x94, 
  /* RLE: 007 Pixels @ 018,017 */ 7, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 004,018 */ 0, 2, 0x8A, 0x52, 0x9A, 0xD6, 
  /* RLE: 009 Pixels @ 006,018 */ 9, 0x9E, 0xF7, 
  /* ABS: 002 Pixels @ 015,018 */ 0, 2, 0x9A, 0xD6, 0x8A, 0x52, 
  /* RLE: 010 Pixels @ 017,018 */ 10, 0x00, 0x00, 
  /* ABS: 009 Pixels @ 006,019 */ 0, 9, 0x8A, 0x52, 0x14, 0xA5, 0x9A, 0xD6, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 0x9A, 0xD6, 0x14, 0xA5, 0x8A, 0x52, 
  /* RLE: 006 Pixels @ 015,019 */ 6, 0x00, 0x00, 
  0
};  // 218 for 420 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_information_background_single = {
  21, // xSize
  20, // ySize
  42, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_information_background_single,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
