/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_default                                          *
* Dimensions:  58 * 46                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_default;

static GUI_CONST_STORAGE unsigned char _acicon_default[] = {
  /* RLE: 768 Pixels @ 000,000 */ 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 6, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 014,013 */ 1, 0x8A, 0x52, 
  /* RLE: 024 Pixels @ 015,013 */ 24, 0x8E, 0x73, 
  /* RLE: 001 Pixels @ 039,013 */ 1, 0x8A, 0x52, 
  /* RLE: 032 Pixels @ 040,013 */ 32, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 014,014 */ 26, 0x8E, 0x73, 
  /* RLE: 032 Pixels @ 040,014 */ 32, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 014,015 */ 26, 0x8E, 0x73, 
  /* RLE: 032 Pixels @ 040,015 */ 32, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 014,016 */ 26, 0x8E, 0x73, 
  /* RLE: 032 Pixels @ 040,016 */ 32, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 014,017 */ 26, 0x8E, 0x73, 
  /* RLE: 032 Pixels @ 040,017 */ 32, 0x00, 0x00, 
  /* RLE: 026 Pixels @ 014,018 */ 26, 0x8E, 0x73, 
  /* RLE: 032 Pixels @ 040,018 */ 32, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,019 */ 20, 0x8E, 0x73, 
  /* RLE: 001 Pixels @ 034,019 */ 1, 0x82, 0x10, 
  /* RLE: 037 Pixels @ 035,019 */ 37, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,020 */ 20, 0x8E, 0x73, 
  /* RLE: 038 Pixels @ 034,020 */ 38, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,021 */ 20, 0x8E, 0x73, 
  /* ABS: 002 Pixels @ 034,021 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,021 */ 7, 0x96, 0xB5, 
  /* RLE: 029 Pixels @ 043,021 */ 29, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,022 */ 20, 0x8E, 0x73, 
  /* ABS: 002 Pixels @ 034,022 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,022 */ 7, 0x96, 0xB5, 
  /* RLE: 029 Pixels @ 043,022 */ 29, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,023 */ 20, 0x8E, 0x73, 
  /* ABS: 002 Pixels @ 034,023 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,023 */ 7, 0x8E, 0x73, 
  /* RLE: 029 Pixels @ 043,023 */ 29, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,024 */ 20, 0x8E, 0x73, 
  /* ABS: 002 Pixels @ 034,024 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,024 */ 7, 0x8E, 0x73, 
  /* RLE: 029 Pixels @ 043,024 */ 29, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,025 */ 20, 0x8E, 0x73, 
  /* ABS: 002 Pixels @ 034,025 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,025 */ 7, 0x8E, 0x73, 
  /* RLE: 029 Pixels @ 043,025 */ 29, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,026 */ 20, 0x8E, 0x73, 
  /* ABS: 002 Pixels @ 034,026 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,026 */ 7, 0x8E, 0x73, 
  /* RLE: 029 Pixels @ 043,026 */ 29, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,027 */ 20, 0x96, 0xB5, 
  /* ABS: 002 Pixels @ 034,027 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,027 */ 7, 0x8E, 0x73, 
  /* RLE: 029 Pixels @ 043,027 */ 29, 0x00, 0x00, 
  /* RLE: 020 Pixels @ 014,028 */ 20, 0x96, 0xB5, 
  /* ABS: 002 Pixels @ 034,028 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,028 */ 7, 0x8E, 0x73, 
  /* RLE: 029 Pixels @ 043,028 */ 29, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 014,029 */ 1, 0x10, 0x84, 
  /* RLE: 019 Pixels @ 015,029 */ 19, 0x96, 0xB5, 
  /* ABS: 002 Pixels @ 034,029 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,029 */ 7, 0x8E, 0x73, 
  /* RLE: 040 Pixels @ 043,029 */ 40, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 025,030 */ 4, 0x96, 0xB5, 
  /* RLE: 007 Pixels @ 029,030 */ 7, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,030 */ 7, 0x8E, 0x73, 
  /* RLE: 040 Pixels @ 043,030 */ 40, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 025,031 */ 4, 0x96, 0xB5, 
  /* RLE: 007 Pixels @ 029,031 */ 7, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,031 */ 7, 0x96, 0xB5, 
  /* RLE: 035 Pixels @ 043,031 */ 35, 0x00, 0x00, 
  /* RLE: 014 Pixels @ 020,032 */ 14, 0x96, 0xB5, 
  /* ABS: 002 Pixels @ 034,032 */ 0, 2, 0x00, 0x00, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 036,032 */ 7, 0x96, 0xB5, 
  /* RLE: 769 Pixels @ 043,032 */ 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 7, 0x00, 0x00, 
  0
};  // 190 for 2668 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_default = {
  58, // xSize
  46, // ySize
  116, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_default,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
