/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_upload_white                                     *
* Dimensions:  12 * 12                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_upload_white;

static GUI_CONST_STORAGE unsigned char _acicon_upload_white[] = {
  /* RLE: 004 Pixels @ 000,000 */ 4, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,000 */ 0, 4, 0x82, 0x10, 0x96, 0xB5, 0x96, 0xB5, 0x82, 0x10, 
  /* RLE: 007 Pixels @ 008,000 */ 7, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 003,001 */ 0, 6, 0x82, 0x10, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 0x82, 0x10, 
  /* RLE: 006 Pixels @ 009,001 */ 6, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 003,002 */ 1, 0x14, 0xA5, 
  /* RLE: 004 Pixels @ 004,002 */ 4, 0x9A, 0xD6, 
  /* RLE: 001 Pixels @ 008,002 */ 1, 0x14, 0xA5, 
  /* RLE: 005 Pixels @ 009,002 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 002,003 */ 1, 0x92, 0x94, 
  /* RLE: 006 Pixels @ 003,003 */ 6, 0x9A, 0xD6, 
  /* ABS: 005 Pixels @ 009,003 */ 0, 5, 0x92, 0x94, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x92, 0x94, 
  /* RLE: 008 Pixels @ 002,004 */ 8, 0x9A, 0xD6, 
  /* ABS: 003 Pixels @ 010,004 */ 0, 3, 0x92, 0x94, 0x00, 0x00, 0x10, 0x84, 
  /* RLE: 010 Pixels @ 001,005 */ 10, 0x9A, 0xD6, 
  /* ABS: 005 Pixels @ 011,005 */ 0, 5, 0x8E, 0x73, 0x14, 0xA5, 0x18, 0xC6, 0x96, 0xB5, 0x18, 0xC6, 
  /* RLE: 004 Pixels @ 004,006 */ 4, 0x9A, 0xD6, 
  /* RLE: 003 Pixels @ 008,006 */ 3, 0x96, 0xB5, 
  /* RLE: 001 Pixels @ 011,006 */ 1, 0x14, 0xA5, 
  /* RLE: 004 Pixels @ 000,007 */ 4, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,007 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 008 Pixels @ 008,007 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,008 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 008 Pixels @ 008,008 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,009 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 008 Pixels @ 008,009 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,010 */ 0, 4, 0x96, 0xB5, 0x9A, 0xD6, 0x9A, 0xD6, 0x96, 0xB5, 
  /* RLE: 008 Pixels @ 008,010 */ 8, 0x00, 0x00, 
  /* ABS: 004 Pixels @ 004,011 */ 0, 4, 0x92, 0x94, 0x9A, 0xD6, 0x9A, 0xD6, 0x92, 0x94, 
  /* RLE: 004 Pixels @ 008,011 */ 4, 0x00, 0x00, 
  0
};  // 146 for 144 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_upload_white = {
  12, // xSize
  12, // ySize
  24, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_upload_white,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
