/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon_usb_link                                         *
* Dimensions:  24 * 24                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmicon_usb_link;

static GUI_CONST_STORAGE unsigned char _acicon_usb_link[] = {
  /* RLE: 059 Pixels @ 000,000 */ 59, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 011,002 */ 1, 0x92, 0x94, 
  /* RLE: 022 Pixels @ 012,002 */ 22, 0x00, 0x00, 
  /* ABS: 003 Pixels @ 010,003 */ 0, 3, 0x0C, 0x63, 0x9E, 0xF7, 0x8E, 0x73, 
  /* RLE: 020 Pixels @ 013,003 */ 20, 0x00, 0x00, 
  /* ABS: 010 Pixels @ 009,004 */ 0, 10, 0x82, 0x10, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 0x82, 0x10, 0x00, 0x00, 0x00, 0x00, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 
  /* RLE: 014 Pixels @ 019,004 */ 14, 0x00, 0x00, 
  /* ABS: 010 Pixels @ 009,005 */ 0, 10, 0x14, 0xA5, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 0x96, 0xB5, 0x00, 0x00, 0x00, 0x00, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 
  /* RLE: 010 Pixels @ 019,005 */ 10, 0x00, 0x00, 
  /* ABS: 007 Pixels @ 005,006 */ 0, 7, 0x10, 0x84, 0x9E, 0xF7, 0x10, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9E, 0xF7, 
  /* RLE: 004 Pixels @ 012,006 */ 4, 0x00, 0x00, 
  /* RLE: 003 Pixels @ 016,006 */ 3, 0x9E, 0xF7, 
  /* RLE: 010 Pixels @ 019,006 */ 10, 0x00, 0x00, 
  /* RLE: 003 Pixels @ 005,007 */ 3, 0x9E, 0xF7, 
  /* RLE: 003 Pixels @ 008,007 */ 3, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 011,007 */ 1, 0x9E, 0xF7, 
  /* RLE: 005 Pixels @ 012,007 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 017,007 */ 1, 0x9E, 0xF7, 
  /* RLE: 011 Pixels @ 018,007 */ 11, 0x00, 0x00, 
  /* ABS: 007 Pixels @ 005,008 */ 0, 7, 0x10, 0x84, 0x9E, 0xF7, 0x10, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9E, 0xF7, 
  /* RLE: 005 Pixels @ 012,008 */ 5, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 017,008 */ 1, 0x9E, 0xF7, 
  /* RLE: 012 Pixels @ 018,008 */ 12, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 006,009 */ 1, 0x18, 0xC6, 
  /* RLE: 004 Pixels @ 007,009 */ 4, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 011,009 */ 1, 0x9E, 0xF7, 
  /* RLE: 004 Pixels @ 012,009 */ 4, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 016,009 */ 0, 2, 0x82, 0x10, 0x9E, 0xF7, 
  /* RLE: 012 Pixels @ 018,009 */ 12, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 006,010 */ 1, 0x9E, 0xF7, 
  /* RLE: 004 Pixels @ 007,010 */ 4, 0x00, 0x00, 
  /* ABS: 007 Pixels @ 011,010 */ 0, 7, 0x9E, 0xF7, 0x00, 0x00, 0x00, 0x00, 0x04, 0x21, 0x10, 0x84, 0x1C, 0xE7, 0x10, 0x84, 
  /* RLE: 012 Pixels @ 018,010 */ 12, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 006,011 */ 1, 0x9E, 0xF7, 
  /* RLE: 004 Pixels @ 007,011 */ 4, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 011,011 */ 0, 6, 0x9E, 0xF7, 0x96, 0xB5, 0x1C, 0xE7, 0x9E, 0xF7, 0x14, 0xA5, 0x08, 0x42, 
  /* RLE: 013 Pixels @ 017,011 */ 13, 0x00, 0x00, 
  /* ABS: 008 Pixels @ 006,012 */ 0, 8, 0x1C, 0xE7, 0x86, 0x31, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9E, 0xF7, 0x86, 0x31, 0x82, 0x10, 
  /* RLE: 016 Pixels @ 014,012 */ 16, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 006,013 */ 0, 6, 0x8A, 0x52, 0x9E, 0xF7, 0x10, 0x84, 0x82, 0x10, 0x00, 0x00, 0x9E, 0xF7, 
  /* RLE: 019 Pixels @ 012,013 */ 19, 0x00, 0x00, 
  /* ABS: 005 Pixels @ 007,014 */ 0, 5, 0x86, 0x31, 0x14, 0xA5, 0x9E, 0xF7, 0x14, 0xA5, 0x9E, 0xF7, 
  /* RLE: 021 Pixels @ 012,014 */ 21, 0x00, 0x00, 
  /* ABS: 003 Pixels @ 009,015 */ 0, 3, 0x82, 0x10, 0x08, 0x42, 0x9E, 0xF7, 
  /* RLE: 023 Pixels @ 012,015 */ 23, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 011,016 */ 1, 0x9E, 0xF7, 
  /* RLE: 022 Pixels @ 012,016 */ 22, 0x00, 0x00, 
  /* ABS: 003 Pixels @ 010,017 */ 0, 3, 0x18, 0xC6, 0x9E, 0xF7, 0x18, 0xC6, 
  /* RLE: 020 Pixels @ 013,017 */ 20, 0x00, 0x00, 
  /* ABS: 005 Pixels @ 009,018 */ 0, 5, 0x0C, 0x63, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 0x0C, 0x63, 
  /* RLE: 019 Pixels @ 014,018 */ 19, 0x00, 0x00, 
  /* ABS: 005 Pixels @ 009,019 */ 0, 5, 0x0C, 0x63, 0x9E, 0xF7, 0x9E, 0xF7, 0x9E, 0xF7, 0x0C, 0x63, 
  /* RLE: 020 Pixels @ 014,019 */ 20, 0x00, 0x00, 
  /* ABS: 003 Pixels @ 010,020 */ 0, 3, 0x96, 0xB5, 0x9E, 0xF7, 0x96, 0xB5, 
  /* RLE: 083 Pixels @ 013,020 */ 83, 0x00, 0x00, 
  0
};  // 290 for 576 pixels

GUI_CONST_STORAGE GUI_BITMAP bmicon_usb_link = {
  24, // xSize
  24, // ySize
  48, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acicon_usb_link,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
