/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: w_dust                                                *
* Dimensions:  108 * 108                                             *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmw_dust;

static GUI_CONST_STORAGE unsigned char _acw_dust[] = {
  /* RLE: 2473 Pixels @ 000,000 */ 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 187, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 097,022 */ 0, 6, 0x86, 0x31, 0xD7, 0xBD, 0xDF, 0xFF, 0xDF, 0xFF, 0xD7, 0xBD, 0x86, 0x31, 
  /* RLE: 010 Pixels @ 103,022 */ 10, 0x00, 0x00, 
  /* RLE: 084 Pixels @ 005,023 */ 84, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 089,023 */ 7, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 096,023 */ 0, 2, 0x86, 0x31, 0xBE, 0xF7, 
  /* RLE: 004 Pixels @ 098,023 */ 4, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 102,023 */ 0, 2, 0xBE, 0xF7, 0x86, 0x31, 
  /* RLE: 009 Pixels @ 104,023 */ 9, 0x00, 0x00, 
  /* RLE: 084 Pixels @ 005,024 */ 84, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 089,024 */ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 096,024 */ 1, 0xD7, 0xBD, 
  /* RLE: 006 Pixels @ 097,024 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 103,024 */ 1, 0xD7, 0xBD, 
  /* RLE: 009 Pixels @ 104,024 */ 9, 0x00, 0x00, 
  /* RLE: 084 Pixels @ 005,025 */ 84, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 089,025 */ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 096,025 */ 1, 0xDF, 0xFF, 
  /* RLE: 006 Pixels @ 097,025 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 103,025 */ 1, 0xDF, 0xFF, 
  /* RLE: 009 Pixels @ 104,025 */ 9, 0x00, 0x00, 
  /* RLE: 084 Pixels @ 005,026 */ 84, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 089,026 */ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 096,026 */ 1, 0xDF, 0xFF, 
  /* RLE: 006 Pixels @ 097,026 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 103,026 */ 1, 0xDF, 0xFF, 
  /* RLE: 009 Pixels @ 104,026 */ 9, 0x00, 0x00, 
  /* RLE: 084 Pixels @ 005,027 */ 84, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 089,027 */ 7, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 096,027 */ 1, 0xD7, 0xBD, 
  /* RLE: 006 Pixels @ 097,027 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 103,027 */ 1, 0xD7, 0xBD, 
  /* RLE: 009 Pixels @ 104,027 */ 9, 0x00, 0x00, 
  /* RLE: 084 Pixels @ 005,028 */ 84, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 089,028 */ 7, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 096,028 */ 0, 2, 0x86, 0x31, 0xBE, 0xF7, 
  /* RLE: 004 Pixels @ 098,028 */ 4, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 102,028 */ 0, 2, 0xBE, 0xF7, 0x86, 0x31, 
  /* RLE: 101 Pixels @ 104,028 */ 101, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 097,029 */ 0, 6, 0x86, 0x31, 0xD7, 0xBD, 0xDF, 0xFF, 0xDF, 0xFF, 0xD7, 0xBD, 0x86, 0x31, 
  /* RLE: 2174 Pixels @ 103,029 */ 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 142, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 009,050 */ 0, 6, 0x86, 0x31, 0xD7, 0xBD, 0xDF, 0xFF, 0xDF, 0xFF, 0xD7, 0xBD, 0x86, 0x31, 
  /* RLE: 101 Pixels @ 015,050 */ 101, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 008,051 */ 0, 2, 0x86, 0x31, 0xBE, 0xF7, 
  /* RLE: 004 Pixels @ 010,051 */ 4, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 014,051 */ 0, 2, 0xBE, 0xF7, 0x86, 0x31, 
  /* RLE: 007 Pixels @ 016,051 */ 7, 0x00, 0x00, 
  /* RLE: 060 Pixels @ 023,051 */ 60, 0xFF, 0xFF, 
  /* RLE: 033 Pixels @ 083,051 */ 33, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 008,052 */ 1, 0xD7, 0xBD, 
  /* RLE: 006 Pixels @ 009,052 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 015,052 */ 1, 0xD7, 0xBD, 
  /* RLE: 007 Pixels @ 016,052 */ 7, 0x00, 0x00, 
  /* RLE: 060 Pixels @ 023,052 */ 60, 0xFF, 0xFF, 
  /* RLE: 033 Pixels @ 083,052 */ 33, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 008,053 */ 1, 0xDF, 0xFF, 
  /* RLE: 006 Pixels @ 009,053 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 015,053 */ 1, 0xDF, 0xFF, 
  /* RLE: 007 Pixels @ 016,053 */ 7, 0x00, 0x00, 
  /* RLE: 060 Pixels @ 023,053 */ 60, 0xFF, 0xFF, 
  /* RLE: 033 Pixels @ 083,053 */ 33, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 008,054 */ 1, 0xDF, 0xFF, 
  /* RLE: 006 Pixels @ 009,054 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 015,054 */ 1, 0xDF, 0xFF, 
  /* RLE: 007 Pixels @ 016,054 */ 7, 0x00, 0x00, 
  /* RLE: 060 Pixels @ 023,054 */ 60, 0xFF, 0xFF, 
  /* RLE: 033 Pixels @ 083,054 */ 33, 0x00, 0x00, 
  /* RLE: 001 Pixels @ 008,055 */ 1, 0xD7, 0xBD, 
  /* RLE: 006 Pixels @ 009,055 */ 6, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 015,055 */ 1, 0xD7, 0xBD, 
  /* RLE: 007 Pixels @ 016,055 */ 7, 0x00, 0x00, 
  /* RLE: 060 Pixels @ 023,055 */ 60, 0xFF, 0xFF, 
  /* RLE: 033 Pixels @ 083,055 */ 33, 0x00, 0x00, 
  /* ABS: 002 Pixels @ 008,056 */ 0, 2, 0x86, 0x31, 0xBE, 0xF7, 
  /* RLE: 004 Pixels @ 010,056 */ 4, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 014,056 */ 0, 2, 0xBE, 0xF7, 0x86, 0x31, 
  /* RLE: 007 Pixels @ 016,056 */ 7, 0x00, 0x00, 
  /* RLE: 060 Pixels @ 023,056 */ 60, 0xFF, 0xFF, 
  /* RLE: 034 Pixels @ 083,056 */ 34, 0x00, 0x00, 
  /* ABS: 006 Pixels @ 009,057 */ 0, 6, 0x86, 0x31, 0xD7, 0xBD, 0xDF, 0xFF, 0xDF, 0xFF, 0xD7, 0xBD, 0x86, 0x31, 
  /* RLE: 2400 Pixels @ 015,057 */ 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 114, 0x00, 0x00, 
  /* RLE: 028 Pixels @ 039,079 */ 28, 0xFF, 0xFF, 
  /* RLE: 080 Pixels @ 067,079 */ 80, 0x00, 0x00, 
  /* RLE: 028 Pixels @ 039,080 */ 28, 0xFF, 0xFF, 
  /* RLE: 080 Pixels @ 067,080 */ 80, 0x00, 0x00, 
  /* RLE: 028 Pixels @ 039,081 */ 28, 0xFF, 0xFF, 
  /* RLE: 080 Pixels @ 067,081 */ 80, 0x00, 0x00, 
  /* RLE: 028 Pixels @ 039,082 */ 28, 0xFF, 0xFF, 
  /* RLE: 080 Pixels @ 067,082 */ 80, 0x00, 0x00, 
  /* RLE: 028 Pixels @ 039,083 */ 28, 0xFF, 0xFF, 
  /* RLE: 080 Pixels @ 067,083 */ 80, 0x00, 0x00, 
  /* RLE: 028 Pixels @ 039,084 */ 28, 0xFF, 0xFF, 
  /* RLE: 2525 Pixels @ 067,084 */ 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 254, 0x00, 0x00, 239, 0x00, 0x00, 
  0
};  // 336 for 11664 pixels

GUI_CONST_STORAGE GUI_BITMAP bmw_dust = {
  108, // xSize
  108, // ySize
  216, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acw_dust,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
