/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     gfx_resources_int.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED ¡°AS IS¡± WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef GFX_RESOURCES_INT_H_FILE
#define GFX_RESOURCES_INT_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif



/*****************************************************************************
 * SECTION: Graphics Configuration
 * Overview:    This defines the size of the buffer used by font functions
 *              to retrieve font data from the external memory. The buffer
 *              size can be increased to accommodate large font sizes.
 *              The user must be aware of the expected glyph sizes of the 
 *              characters stored in the font table. 
 *              To modify the size used, declare this macro in the 
 *              GraphicsConfig.h file with the desired size.
 *
 * #define GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE     (816)
 *****************************************************************************/

/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: phicomm
 * Description:  186x52 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR phicomm;
#define phicomm_WIDTH     (186)
#define phicomm_HEIGHT    (52)
#define phicomm_SIZE      (10190)
/*****************************************************************************
 * SECTION:  JPEGS
 *****************************************************************************/

/*********************************
 * JPEG Structure
 * Label: icon_download_white
 * Description:  12x12 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_download_white;
#define icon_download_white_WIDTH     (12)
#define icon_download_white_HEIGHT    (12)
#define icon_download_white_SIZE      (734)
/*********************************
 * JPEG Structure
 * Label: icon_upload_white
 * Description:  12x12 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_upload_white;
#define icon_upload_white_WIDTH     (12)
#define icon_upload_white_HEIGHT    (12)
#define icon_upload_white_SIZE      (707)
/*********************************
 * JPEG Structure
 * Label: icon_1jia
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_1jia;
#define icon_1jia_WIDTH     (58)
#define icon_1jia_HEIGHT    (46)
#define icon_1jia_SIZE      (901)
/*********************************
 * JPEG Structure
 * Label: icon_360
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_360;
#define icon_360_WIDTH     (58)
#define icon_360_HEIGHT    (46)
#define icon_360_SIZE      (941)
/*********************************
 * JPEG Structure
 * Label: icon_asus
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_asus;
#define icon_asus_WIDTH     (58)
#define icon_asus_HEIGHT    (46)
#define icon_asus_SIZE      (1021)
/*********************************
 * JPEG Structure
 * Label: icon_coolpad
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_coolpad;
#define icon_coolpad_WIDTH     (58)
#define icon_coolpad_HEIGHT    (46)
#define icon_coolpad_SIZE      (1016)
/*********************************
 * JPEG Structure
 * Label: icon_dell
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_dell;
#define icon_dell_WIDTH     (58)
#define icon_dell_HEIGHT    (46)
#define icon_dell_SIZE      (1242)
/*********************************
 * JPEG Structure
 * Label: icon_haier
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_haier;
#define icon_haier_WIDTH     (58)
#define icon_haier_HEIGHT    (46)
#define icon_haier_SIZE      (1262)
/*********************************
 * JPEG Structure
 * Label: icon_hasee
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_hasee;
#define icon_hasee_WIDTH     (58)
#define icon_hasee_HEIGHT    (46)
#define icon_hasee_SIZE      (1035)
/*********************************
 * JPEG Structure
 * Label: icon_honor
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_honor;
#define icon_honor_WIDTH     (58)
#define icon_honor_HEIGHT    (46)
#define icon_honor_SIZE      (1031)
/*********************************
 * JPEG Structure
 * Label: icon_hp
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_hp;
#define icon_hp_WIDTH     (58)
#define icon_hp_HEIGHT    (46)
#define icon_hp_SIZE      (1022)
/*********************************
 * JPEG Structure
 * Label: icon_htc
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_htc;
#define icon_htc_WIDTH     (58)
#define icon_htc_HEIGHT    (46)
#define icon_htc_SIZE      (1133)
/*********************************
 * JPEG Structure
 * Label: icon_huawei
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_huawei;
#define icon_huawei_WIDTH     (58)
#define icon_huawei_HEIGHT    (46)
#define icon_huawei_SIZE      (1072)
/*********************************
 * JPEG Structure
 * Label: icon_iPhone
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_iPhone;
#define icon_iPhone_WIDTH     (58)
#define icon_iPhone_HEIGHT    (46)
#define icon_iPhone_SIZE      (953)
/*********************************
 * JPEG Structure
 * Label: icon_lenovo
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_lenovo;
#define icon_lenovo_WIDTH     (58)
#define icon_lenovo_HEIGHT    (46)
#define icon_lenovo_SIZE      (1015)
/*********************************
 * JPEG Structure
 * Label: icon_letv
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_letv;
#define icon_letv_WIDTH     (58)
#define icon_letv_HEIGHT    (46)
#define icon_letv_SIZE      (1134)
/*********************************
 * JPEG Structure
 * Label: icon_lg
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_lg;
#define icon_lg_WIDTH     (58)
#define icon_lg_HEIGHT    (46)
#define icon_lg_SIZE      (1022)
/*********************************
 * JPEG Structure
 * Label: icon_meitu
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_meitu;
#define icon_meitu_WIDTH     (58)
#define icon_meitu_HEIGHT    (46)
#define icon_meitu_SIZE      (1052)
/*********************************
 * JPEG Structure
 * Label: icon_meizu
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_meizu;
#define icon_meizu_WIDTH     (58)
#define icon_meizu_HEIGHT    (46)
#define icon_meizu_SIZE      (1043)
/*********************************
 * JPEG Structure
 * Label: icon_oppo
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_oppo;
#define icon_oppo_WIDTH     (58)
#define icon_oppo_HEIGHT    (46)
#define icon_oppo_SIZE      (1001)
/*********************************
 * JPEG Structure
 * Label: icon_phicomm
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_phicomm;
#define icon_phicomm_WIDTH     (58)
#define icon_phicomm_HEIGHT    (46)
#define icon_phicomm_SIZE      (1030)
/*********************************
 * JPEG Structure
 * Label: icon_samsung
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_samsung;
#define icon_samsung_WIDTH     (58)
#define icon_samsung_HEIGHT    (46)
#define icon_samsung_SIZE      (1040)
/*********************************
 * JPEG Structure
 * Label: icon_smartisan
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_smartisan;
#define icon_smartisan_WIDTH     (58)
#define icon_smartisan_HEIGHT    (46)
#define icon_smartisan_SIZE      (1001)
/*********************************
 * JPEG Structure
 * Label: icon_sony
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_sony;
#define icon_sony_WIDTH     (58)
#define icon_sony_HEIGHT    (46)
#define icon_sony_SIZE      (1043)
/*********************************
 * JPEG Structure
 * Label: icon_tcl
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_tcl;
#define icon_tcl_WIDTH     (58)
#define icon_tcl_HEIGHT    (46)
#define icon_tcl_SIZE      (831)
/*********************************
 * JPEG Structure
 * Label: icon_thinkpad
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_thinkpad;
#define icon_thinkpad_WIDTH     (58)
#define icon_thinkpad_HEIGHT    (46)
#define icon_thinkpad_SIZE      (1124)
/*********************************
 * JPEG Structure
 * Label: icon_tongfang
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_tongfang;
#define icon_tongfang_WIDTH     (58)
#define icon_tongfang_HEIGHT    (46)
#define icon_tongfang_SIZE      (901)
/*********************************
 * JPEG Structure
 * Label: icon_vivo
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_vivo;
#define icon_vivo_WIDTH     (58)
#define icon_vivo_HEIGHT    (46)
#define icon_vivo_SIZE      (1095)
/*********************************
 * JPEG Structure
 * Label: icon_windowsphone
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_windowsphone;
#define icon_windowsphone_WIDTH     (58)
#define icon_windowsphone_HEIGHT    (46)
#define icon_windowsphone_SIZE      (906)
/*********************************
 * JPEG Structure
 * Label: icon_xiaomi
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_xiaomi;
#define icon_xiaomi_WIDTH     (58)
#define icon_xiaomi_HEIGHT    (46)
#define icon_xiaomi_SIZE      (975)
/*********************************
 * JPEG Structure
 * Label: icon_zte
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_zte;
#define icon_zte_WIDTH     (58)
#define icon_zte_HEIGHT    (46)
#define icon_zte_SIZE      (1053)
/*********************************
 * JPEG Structure
 * Label: icon_hint_disconnected
 * Description:  30x30 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_hint_disconnected;
#define icon_hint_disconnected_WIDTH     (30)
#define icon_hint_disconnected_HEIGHT    (30)
#define icon_hint_disconnected_SIZE      (1052)
/*********************************
 * JPEG Structure
 * Label: icon_information_background_double
 * Description:  30x20 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_information_background_double;
#define icon_information_background_double_WIDTH     (30)
#define icon_information_background_double_HEIGHT    (20)
#define icon_information_background_double_SIZE      (869)
/*********************************
 * JPEG Structure
 * Label: icon_information_background_single
 * Description:  21x20 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_information_background_single;
#define icon_information_background_single_WIDTH     (21)
#define icon_information_background_single_HEIGHT    (20)
#define icon_information_background_single_SIZE      (851)
/*********************************
 * JPEG Structure
 * Label: icon_recovery
 * Description:  100x100 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_recovery;
#define icon_recovery_WIDTH     (100)
#define icon_recovery_HEIGHT    (100)
#define icon_recovery_SIZE      (1576)
/*********************************
 * JPEG Structure
 * Label: icon_wifi_close
 * Description:  100x100 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_wifi_close;
#define icon_wifi_close_WIDTH     (100)
#define icon_wifi_close_HEIGHT    (100)
#define icon_wifi_close_SIZE      (2115)
/*********************************
 * JPEG Structure
 * Label: icon_wifi_open
 * Description:  100x100 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_wifi_open;
#define icon_wifi_open_WIDTH     (100)
#define icon_wifi_open_HEIGHT    (100)
#define icon_wifi_open_SIZE      (1713)
/*********************************
 * JPEG Structure
 * Label: icon_default
 * Description:  58x46 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_default;
#define icon_default_WIDTH     (58)
#define icon_default_HEIGHT    (46)
#define icon_default_SIZE      (1026)
/*********************************
 * JPEG Structure
 * Label: icon_two_dimensional_code
 * Description:  100x100 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_two_dimensional_code;
#define icon_two_dimensional_code_WIDTH     (100)
#define icon_two_dimensional_code_HEIGHT    (100)
#define icon_two_dimensional_code_SIZE      (6977)
/*********************************
 * JPEG Structure
 * Label: w_cloudy
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_cloudy;
#define w_cloudy_WIDTH     (108)
#define w_cloudy_HEIGHT    (108)
#define w_cloudy_SIZE      (2844)
/*********************************
 * JPEG Structure
 * Label: w_dust
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_dust;
#define w_dust_WIDTH     (108)
#define w_dust_HEIGHT    (108)
#define w_dust_SIZE      (1986)
/*********************************
 * JPEG Structure
 * Label: w_foggy
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_foggy;
#define w_foggy_WIDTH     (108)
#define w_foggy_HEIGHT    (108)
#define w_foggy_SIZE      (2279)
/*********************************
 * JPEG Structure
 * Label: w_haze
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_haze;
#define w_haze_WIDTH     (108)
#define w_haze_HEIGHT    (108)
#define w_haze_SIZE      (2845)
/*********************************
 * JPEG Structure
 * Label: w_overcast
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_overcast;
#define w_overcast_WIDTH     (108)
#define w_overcast_HEIGHT    (108)
#define w_overcast_SIZE      (2355)
/*********************************
 * JPEG Structure
 * Label: w_rain
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_rain;
#define w_rain_WIDTH     (108)
#define w_rain_HEIGHT    (108)
#define w_rain_SIZE      (2742)
/*********************************
 * JPEG Structure
 * Label: w_windy
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_windy;
#define w_windy_WIDTH     (108)
#define w_windy_HEIGHT    (108)
#define w_windy_SIZE      (2335)
/*********************************
 * JPEG Structure
 * Label: w_sun
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_sun;
#define w_sun_WIDTH     (108)
#define w_sun_HEIGHT    (108)
#define w_sun_SIZE      (2941)
/*********************************
 * JPEG Structure
 * Label: w_snow
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_snow;
#define w_snow_WIDTH     (108)
#define w_snow_HEIGHT    (108)
#define w_snow_SIZE      (2778)
/*********************************
 * JPEG Structure
 * Label: w_unknown
 * Description:  108x108 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_unknown;
#define w_unknown_WIDTH     (108)
#define w_unknown_HEIGHT    (108)
#define w_unknown_SIZE      (2445)
/*********************************
 * JPEG Structure
 * Label: icon_update
 * Description:  72x72 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_update;
#define icon_update_WIDTH     (72)
#define icon_update_HEIGHT    (72)
#define icon_update_SIZE      (1803)
/*********************************
 * JPEG Structure
 * Label: w_locationfailed
 * Description:  82x82 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR w_locationfailed;
#define w_locationfailed_WIDTH     (82)
#define w_locationfailed_HEIGHT    (82)
#define w_locationfailed_SIZE      (2252)
/*********************************
 * JPEG Structure
 * Label: icon_wifi
 * Description:  21x20 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_wifi;
#define icon_wifi_WIDTH     (21)
#define icon_wifi_HEIGHT    (20)
#define icon_wifi_SIZE      (849)
/*********************************
 * JPEG Structure
 * Label: icon_usb_link
 * Description:  24x24 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_usb_link;
#define icon_usb_link_WIDTH     (24)
#define icon_usb_link_HEIGHT    (24)
#define icon_usb_link_SIZE      (867)
/*********************************
 * JPEG Structure
 * Label: icon_visitor
 * Description:  21x20 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_visitor;
#define icon_visitor_WIDTH     (21)
#define icon_visitor_HEIGHT    (20)
#define icon_visitor_SIZE      (902)
/*********************************
 * JPEG Structure
 * Label: icon_apmode
 * Description:  80x80 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR icon_apmode;
#define icon_apmode_WIDTH     (80)
#define icon_apmode_HEIGHT    (80)
#define icon_apmode_SIZE      (2393)
/*****************************************************************************
 * SECTION:  Fonts
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: font18
 * Description:  Height: 22 pixels, 2 bits per pixel, Range: ' ' to '£º'
 ***********************************/
extern const GFX_RESOURCE_HDR font18;
#define font18_SIZE    (8546)
/*********************************
 * TTF Font File Structure
 * Label: font26
 * Description:  Height: 32 pixels, 2 bits per pixel, Range: ' ' to 'Æµ'
 ***********************************/
extern const GFX_RESOURCE_HDR font26;
#define font26_SIZE    (22272)
/*********************************
 * TTF Font File Structure
 * Label: font14
 * Description:  Height: 18 pixels, 2 bits per pixel, Range: ' ' to '£º'
 ***********************************/
extern const GFX_RESOURCE_HDR font14;
#define font14_SIZE    (6312)
/*********************************
 * TTF Font File Structure
 * Label: font20
 * Description:  Height: 24 pixels, 2 bits per pixel, Range: ' ' to '±Õ'
 ***********************************/
extern const GFX_RESOURCE_HDR font20;
#define font20_SIZE    (8844)
/*********************************
 * TTF Font File Structure
 * Label: font48
 * Description:  Height: 68 pixels, 2 bits per pixel, Range: ' ' to '¡ã'
 ***********************************/
extern const GFX_RESOURCE_HDR font48;
#define font48_SIZE    (44936)
/*********************************
 * TTF Font File Structure
 * Label: font16
 * Description:  Height: 19 pixels, 2 bits per pixel, Range: ' ' to '£º'
 ***********************************/
extern const GFX_RESOURCE_HDR font16;
#define font16_SIZE    (8769)
/*********************************
 * TTF Font File Structure
 * Label: font22
 * Description:  Height: 27 pixels, 2 bits per pixel, Range: ' ' to 'Æµ'
 ***********************************/
extern const GFX_RESOURCE_HDR font22;
#define font22_SIZE    (9708)
/*********************************
 * TTF Font File Structure
 * Label: alert_font24
 * Description:  Height: 29 pixels, 2 bits per pixel, Range: ' ' to '±Õ'
 ***********************************/
extern const GFX_RESOURCE_HDR alert_font24;
#define alert_font24_SIZE    (15526)
/*********************************
 * TTF Font File Structure
 * Label: city18
 * Description:  Height: 22 pixels, 2 bits per pixel, Range: ' ' to 'Áú'
 ***********************************/
extern const GFX_RESOURCE_HDR city18;
#define city18_SIZE    (133262)
/*********************************
 * TTF Font File Structure
 * Label: weather18
 * Description:  Height: 22 pixels, 2 bits per pixel, Range: ' ' to 'Áú'
 ***********************************/
extern const GFX_RESOURCE_HDR weather18;
#define weather18_SIZE    (10370)
/*********************************
 * TTF Font File Structure
 * Label: font_pf42
 * Description:  Height: 60 pixels, 2 bits per pixel, Range: ' ' to ''
 ***********************************/
extern const GFX_RESOURCE_HDR font_pf42;
#define font_pf42_SIZE    (35192)
#endif

